services:
  database:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD="Km9@v-A6F%FdSt!6ja8"
    networks:
      kanmi_system:
        aliases:
          - sql.backend.seq
    volumes:
      - ./common/init.sql:/docker-entrypoint-initdb.d/setup.sql
      - db_data:/var/lib/mysql
    restart: unless-stopped

  web:
    build:
      context: ./sequenzia-php
    ports:
      - 4000:4000
    networks:
      kanmi_system:
        aliases:
          - web.services.seq
    depends_on:
      - database
    volumes:
      - ./data/:/php-sequenzia/public/data/

    restart: on-failure

networks:
  kanmi_system:
    ipam:
      driver: default
      config:
        - subnet: 192.168.99.0/24
    driver_opts:
      com.docker.networks.bridge.name: br-sequenzia

volumes:
  db_data:
  seq_data:
